# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# Additional configuration for OpenTelemetry Collector

processors:
  attributes:
    actions:
      - key: environment
        value: development
        action: insert
      - key: deployment.environment
        value: development
        action: insert

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    traces:
      processors: [attributes, batch, memory_limiter]
    metrics:
      processors: [attributes, batch, memory_limiter]
    logs:
      processors: [attributes, batch, memory_limiter]