# docker-compose.yml (in project root: dzinza-python/)
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"
  
services:

  app_ui:
    image: dzinza-app-ui:${DZINZA_VERSION:-latest}
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        VERSION: ${DZINZA_VERSION:-latest}
        VITE_API_BASE_URL: 'http://backend:8090/api'
    container_name: dzinza-app-ui
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    logging: *logging # Using the YAML anchor for logging
    networks:
      - dzinza-net
