# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: jaeger
      timeInterval: 5s

  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      nodeGraph:
        enabled: true

  - name: OpenSearch
    type: grafana-opensearch-datasource
    uid: opensearch
    access: proxy
    url: http://opensearch:9200
    editable: true
    jsonData:
      database: "[otel-*]"
      timeField: "@timestamp"
      version: "2.0.0"