"""update_event_model_person_id_nullable_add_related_ids

Revision ID: 0007
Revises: 0006
Create Date: 2024-04-08 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006' # Points to the migration for tree privacy settings
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'person_id',
               existing_type=postgresql.UUID(as_uuid=True),
               nullable=True)
    op.add_column('events', sa.Column('related_person_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Making person_id non-nullable again could fail if NULLs were introduced.
    # A production downgrade might require a data cleansing step or setting a default.
    op.alter_column('events', 'person_id',
               existing_type=postgresql.UUID(as_uuid=True),
               nullable=False)
    op.drop_column('events', 'related_person_ids')
    # ### end Alembic commands ###
