"""add_display_order_to_person

Revision ID: b5f1932d584a
Revises: globalize_person_models
Create Date: 2025-06-01 02:57:58.836007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f1932d584a'
down_revision: Union[str, None] = '29bd3cc00267' # Corrected down_revision
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('display_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_people_display_order'), 'people', ['display_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_display_order'), table_name='people')
    op.drop_column('people', 'display_order')
    # ### end Alembic commands ###
